### ISSUE TITLE
回国的微信规则貌似有些问题

### ISSUE THREAD

**Issue by Talent30** [tudi1909/Surge_rules#10]
启用后微信无法收取信息。

**Comment by tudi1909** [comment]
请尝试将
USER-AGENT,WeChat*,Proxy
改为
USER-AGENT,WeChat*,Proxy,force-remote-dns
进行测试下

**Comment by Talent30** [comment]
tes

**Comment by Talent30** [comment]
Test USER-AGENT,WeChat*,Proxy,force-remote-dns Fail
USER-AGENT,WeChat*,DIRECT Pass
建议修改规则，感谢您的帮助与分享。

**Comment by tudi1909** [comment]
ok,感谢反馈！我收录下！你微博id多少我备注下

**Comment by Talent30** [comment]
备注推特：JonSun30就好了，谢谢。
