### ISSUE TITLE
新浪微博国际版报错

### ISSUE THREAD

**Issue by SirM2z** [tudi1909/Surge_rules#13]
证书已装

![image](https://user-images.githubusercontent.com/12137804/34402253-6ec8b904-ebdb-11e7-82fc-cf0643734bef.png)

**Comment by tudi1909** [comment]
请您再次确认，设置-关于本机-信任是否已经开启

**Comment by SirM2z** [comment]
可以了，没有开启（关于本机中的信任）造成的
