### ISSUE TITLE
全能规则致微博国际版无法联网

### ISSUE THREAD

**Issue by n00d1e5** [tudi1909/Surge_rules#15]
刷新 Timeline 提示 NSURLErrorDomain error 1012。
未改动配置文件，AS 和 Proxy 全部 Direct。

另咨询，请教如何将 easylist 写入 surge 规则？是否可以使用如下来源于 Easylist 规则举例？谢谢。

&act=ads_

-ad-180x150px.

.ad-traffic.

/ad-modules/*

###AdBox2

||007-gateway.com^$third-party

非常感谢

**Comment by tudi1909** [comment]
1.微博问题请按照说明检查下你的证书安装是否正确

2.Surge 不能处理HTML代码级别，所以放弃吧

**Comment by n00d1e5** [comment]
已正确安装证书。

微博国际版无法更新报错信息：NSURLErrorDomain -1012。

应该是规则解析后导致相关域名无法访问。

**Comment by crimeg** [comment]
我也是这个问题，微博国际版无法刷新

**Comment by crimeg** [comment]
主机名里面删除api.weibo.cn就好了

**Comment by n00d1e5** [comment]
我真的好奇你们如何做到正常的......

安装证书： 配置 - 编辑配置 - HTTPS 解密 - 安装证书
信任证书： 设置 - 通用 - 关于本机 - 证书信任设置 - 信任
刷新国际版微博： NSURLErrorDomain -1012。

我只能手动删除 weibo 相关规则......
