### ISSUE TITLE
您好，一直在用您的规则，有点问题想向您询问一下。

### ISSUE THREAD

**Issue by Fsick** [tudi1909/Surge_rules#9]
关于托管规则，因为我的节点比较多，所以每次您更新规则之后我都要复制粘贴好一阵子，能不能有什么方法在您更新规则之后通过托管替换我的节点呢？谢谢您🙏

**Comment by tudi1909** [comment]
其实很简单，本次配置并运行成功后，复制[Proxy]标签及[Proxy Group]下所有内容，保存好，下次粘贴即可！

**Comment by Fsick** [comment]
我知道这个方法😊只是在想能不能直接托管替换 嘿嘿😁

**Comment by tudi1909** [comment]
暂无此打算做托管自动配置，github上面有很多成熟方案了，你可以配置好以后直接下载就行，例如https://github.com/yourtion/SurgeConfigGenerator

**Comment by Fsick** [comment]
没事没事  我只是问问  谢谢🙏
